num1=int(input("enter 1st number:"))
num2=int(input("enter 2nd number:"))
print(num1+num2)
print(num1-num2)
print(num1/num2)
print(num1*num2)
print(num1%num2)
print(num1**num2)#power(30 power 10)
print(num1//num2)
